"""Add logged_expiry_at to insurance_policy

Revision ID: ffcbe8fd14f3
Revises: 281d4c64ffef
Create Date: 2025-10-23 20:18:48.454199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffcbe8fd14f3'
down_revision: Union[str, Sequence[str], None] = '281d4c64ffef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insurance_policy', 'logged_expiry_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
